-- Migration: Add is_provisional flag to speech_versions
-- Provisional speeches are auto-generated by AI, shared across all users in the org.
-- When gerente publishes their own speech, provisional is replaced.

ALTER TABLE speech_versions
  ADD COLUMN IF NOT EXISTS is_provisional BOOLEAN DEFAULT false;
